name: Test SSH

on: 
  push:
    branches: 
      - main
jobs:
  build_ubuntu:
    uses: 'cuongnh97/github-actions/.github/workflows/ssh.yml@0'
    with:
      host: 127.0.0.1
      username: test
      ssh_key: "Test luon"
  test_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Display result
        run: cat ~/.ssh/staging.key
