name: Test SSH

on: 
  push:
    branches: 
      - master
jobs:
  test_ssh:
    name: Testing run ssh
    runs-on: ubuntu-latest
    
    steps:
      - name: Test workflow
        uses: ./.github/workflows/ssh.yml@
        with:
          host: 127.0.0.1
          username: test
          ssh_key: "Test luon"
      - name: echo ssh key
        run: |
          cat ~/.ssh/staging.key
