name: Test SSH

on: 
  push:
    branches: 
      - main
jobs:
  test_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        uses: 'cuongnh97/github-actions@main'
        with:
          host: 127.0.0.1
          username: test
          ssh_key: "Test luon"
    
      - name: Display result
        run: cat ~/.ssh/staging.key
