name: Test SSH

on: 
  push:
    branches: 
      - main
jobs:
  test_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        uses: 'cuongnh97/github-actions@main'
        with:
          host: ${{ secrets.PUBLIC_IP_GCE }}
          username: ${{ secrets.USER_SSH }}
          ssh_key:  ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Connect to GCE
        run: ssh staging 'cat ~/test_file.txt'
